"""Export the world model's outcome rules for live tickets' "60 days later" (demo spec §19.3).

The web app simulates what Stripe and the subscription system would send after a live decision, with the
same probabilities and timings the history was generated with. This writes them to one JSON file so both
sides stay in sync:

    uv run python -m rationode.sim.outcome_model
"""

import json

from rationode.db import REPO_ROOT
from rationode.sim import world as w

OUT = REPO_ROOT / "web" / "src" / "data" / "outcome-model.json"


def model() -> dict:
    return {
        "_source": "pipeline/src/rationode/sim/world.py (generated by rationode.sim.outcome_model; do not edit)",
        "long_tenure_months": w.LONG_TENURE_MONTHS,
        "partial_refund_share": w.PARTIAL_REFUND_SHARE,
        # final option -> [dispute_prob_long, dispute_prob_short, churn_prob_long, churn_prob_short]
        "complaint_outcomes": {k: list(v) for k, v in w.COMPLAINT_OUTCOMES.items()},
        "too_expensive_deny": list(w.TOO_EXPENSIVE_DENY),
        "dispute_category_after_complaint": {k: [list(x) for x in v] for k, v in w.DISPUTE_CATEGORY_AFTER_COMPLAINT.items()},
        "monthly_renewal_if_no_churn": w.MONTHLY_RENEWAL_IF_NO_CHURN,
        # days after the decision (as generate.py: dispute later(5, 60), churn later(10, 45), renewal later(25, 35))
        "days": {"dispute": [5, 60], "churn": [10, 45], "renewal": [25, 35]},
    }


def main() -> None:
    OUT.write_text(json.dumps(model(), indent=1) + "\n")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
